/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:754388fd-0c01-4e26-ab02-ccee7e5085f6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3ijBawsro",
    "aws_user_pools_web_client_id": "5vk7e4ihrqs4l7sadhg644qh55",
    "oauth": {}
};


export default awsmobile;
